<a href="https://colab.research.google.com/github/Vishnupriya786/Mathematics-for-Machine-Learning/blob/main/Diagonal-Matrix/Diagonal_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np

In [33]:
matrix = np.arange(1,17).reshape((4,4))
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [35]:
diagonalElements = np.diag(matrix)
print(diagonalElements)

[ 1  6 11 16]


In [36]:
diagonalMatrix = np.diag(diagonalElements)
print("The off-diagonal elements are zero for diagonal matrix")
print(diagonalMatrix)

The off-diagonal elements are zero for diagonal matrix
[[ 1  0  0  0]
 [ 0  6  0  0]
 [ 0  0 11  0]
 [ 0  0  0 16]]
