<a href="https://colab.research.google.com/github/Vishnupriya786/Mathematics-for-Machine-Learning/blob/main/Matrix/Dimensions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
matrix3X1 = np.array([[1],[2],[3]])
print("matrix 3X1 represents 3 rows and 1 column")
print(matrix3X1)

matrix 3X1 represents 3 rows and 1 column
[[1]
 [2]
 [3]]


In [10]:
matrix3X3 = np.array([[1,2,3],[2,4,5],[3,4,6]])
print("matrix 3X3 represents 3 rows and 3 column")
print(matrix3X3)

matrix 3X3 represents 3 rows and 3 column
[[1 2 3]
 [2 4 5]
 [3 4 6]]
