<a href="https://colab.research.google.com/github/Vishnupriya786/Mathematics-for-Machine-Learning/blob/main/Matrix/Index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [15]:
matrix3X3 = np.array([[1,2,3],[2,4,5],[3,4,6]])
print("Index for row and column range from 0")
print(matrix3X3)
print(matrix3X3[1][2])

Index for row and column range from 0
[[1 2 3]
 [2 4 5]
 [3 4 6]]
5
