<a href="https://colab.research.google.com/github/Vishnupriya786/Mathematics-for-Machine-Learning/blob/main/Triangular_Matrix/Lower_Triangular_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
lowerTriangularMatrix = np.tril([[1,2,3],[4,5,6],[7,6,5]])
print(lowerTriangularMatrix)

[[1 0 0]
 [4 5 0]
 [7 6 5]]
