<a href="https://colab.research.google.com/github/Vishnupriya786/Mathematics-for-Machine-Learning/blob/main/Triangular_Matrix/Upper_Triangular_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np

In [49]:
upperTriangularMatrix = np.triu([[1,2,3],[4,5,6],[7,6,5]])
print(upperTriangularMatrix)

[[1 2 3]
 [0 5 6]
 [0 0 5]]
